### ISSUE TITLE
License of camera footage itself

### ISSUE THREAD

**Issue by pboes** [AidanWelch/OpenTrafficCamMap#15]
Dear Aidan, 

thanks for the great work behind this repo. I have a licensing question. While the code is under MIT license, I wonder whether this extends to the footage of the traffic cameras themselves. If not, which terms apply? 

Cheers, Paul

**Comment by AidanWelch** [comment]
Thanks,

Nope, it does not, unfortunately.  And, actually that would have be resolved through contacting or finding if their is any information regarding that with individual DOTs.  This is just a list of links to their cameras, the footage is still theirs.

**Comment by pboes** [comment]
Thanks for the reply @AidanWelch

**Comment by pboes** [comment]
Hi @AidanWelch, sorry for bringing this back up but I'm unsure about how to proceed. I understand that you provide just the list, but I wonder how other users of the list deal with this? What am I allowed to do without tracking down the camera owners and getting their permission and what not? For example, am I allowed to watch the camera footage on the interactive map without asking for their permission? Am I allowed to feed the footage into another application as long as I don't record and save any of the footage? What rights do the owners allow me to do just by virtue of adding their camera to the list? Any help here would be much appreciated.

**Comment by AidanWelch** [comment]
It's no problem, but these cameras aren't added by the owners to the list, they are added by myself and other developers of this project to the list.  We scrape them from (generally) government websites where they are publicly available.  So, the footage is the property of the individual government DOTs.  But, since these are publicly accessible URIs you are free to view them, stream them.  Now technically, whether or not you can download them would be determined by each individual copyright holder, but I would be very surprised if any government agency had a problem with downloading the footage, but its possible.

**Comment by AidanWelch** [comment]
As for using the footage without saving it?  From my perspective that should be permissible, but I am not knowledgeable on copyright law to say for certain, but likewise I doubt any of the copyright holders would mind, as none of them are monetizing the footage and instead are just providing it for public use.

**Comment by pboes** [comment]
Thanks @AidanWelch, I then might get in touch with DOTs if I want to be 100% safe. Thanks for clarifying!

**Comment by AidanWelch** [comment]
@pboes Okay, and I'm interested to hear their answers!
